### ISSUE TITLE
Compatibility with Japanese Support Plugin

### ISSUE THREAD

**Issue by Bluemoondragon07** [ckilb/koreader-dictionarymode#1]
Hello. This plug-in is amazing! 

However, there is one problem I have with the plug-in. To see it in action, open a file with Japanese text (I can provide one if needed), install a Japanese dictionary in-app, and long press on some words. You will notice that it selects whole words or phrases. This is KOreader's Japanese Support plug-in in action, splitting the characters into words.

Then, use this plug-in with a single tap. Notice that it only selects one character. 

Is there a way to trigger the Japanese Support plug-in on tap, just like the regular dictionary action does?

You in no way are obligated to add support, but, for me and some other people it would be really cool!

Anyway, have a great day and please think about it! Your plugin helps me a lot for my high school studies, but better support for Japanese would make it even better!

**Comment by ckilb** [comment]
Hey,

could you provide such a book so I can test with it?

**Comment by Bluemoondragon07** [comment]
Thank you so much! Here is a file you can download from Google drive: https://drive.google.com/file/d/1LXnKbfpxxW-GOn9b8xMbD8NJ0xfNuzdh/view?usp=drivesdk

**Comment by ckilb** [comment]
i just added a commit that enables support for languagesupport plugins like the japanese one. feel free to test!

**Comment by Bluemoondragon07** [comment]
Wow! Thank you so much, this means a lot to me! I usually use an app called Jidoujisho for Japanese because it has a tap dictionary but maaan that app is slow. Now, you made KOreader perfect. My dream of having a tap dictionary in KOreader for Japanese is a reality!

Again, thank you so much. I am so happy.
